apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rtmp-server
  template:
    metadata:
      labels:
        app: nginx-rtmp-server
    spec:
      containers:
      - name: nginx-rtmp-server
        image: nginx-rtmp-server:latest  
        ports:
        - containerPort: 80
        - containerPort: 1935
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp-server
spec:
  selector:
    app: nginx-rtmp-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  
  - name: rtmp
    protocol: TCP
    port: 1935
    targetPort: 1935
    nodePort: 31935  
  - name: custom
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32000  
  type: NodePort