name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run build script
      run: |
        cd platform
        ./build.sh

    - name: Build Docker image
      run: |
        docker build -t nginx-rtmp-server:latest .

    - name: Set up Kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.11.1

    - name: Load Docker image into Kind
      run: kind load docker-image nginx-rtmp-server:latest

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f kubernetes/deployment.yaml

    - name: Update Kubernetes deployment
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "${KUBE_CONFIG_DATA}" | base64 --decode > $HOME/.kube/config
        kubectl set image deployment/nginx-rtmp-server nginx-rtmp-server=nginx-rtmp-server:latest --record
        kubectl rollout status deployment/nginx-rtmp-server || kubectl logs deployment/nginx-rtmp-server